### ISSUE TITLE
Демо-страница

### ISSUE THREAD

**Issue by Hahahayabanan** [wzdorowa/jQuery-slider#20]
Повторяющийся код. + здесь внутренняя структура и код для сразу несколько блоков, каждый блок должен быть в  отдельном миксине

![image](https://user-images.githubusercontent.com/43137324/124626844-b4c9b000-de87-11eb-8ee1-9e74fdd6231a.png)

Модули должны использоваться из node_modules. [п.4.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#4.3) 
Сборщик не подхватывает entry point для js автоматически?

![image](https://user-images.githubusercontent.com/43137324/124627134-f8241e80-de87-11eb-90e1-ca1ac439f0c1.png)

**Comment by Hahahayabanan** [comment]
Динамическое имя блока?)

![image](https://user-images.githubusercontent.com/43137324/124628797-80ef8a00-de89-11eb-9f3d-848c06714300.png)


Что будет, если не передать в миксин ничего и параметры примут значение по-умолчанию?

![image](https://user-images.githubusercontent.com/43137324/124628684-63babb80-de89-11eb-8983-595e841e58f8.png)

**Comment by Hahahayabanan** [comment]
Тут тоже должно быть ООП

![image](https://user-images.githubusercontent.com/43137324/124631688-4b986b80-de8c-11eb-8cbc-4f7bd150d98d.png)

**Comment by Olga-Skoroded** [comment]
Теперь модификаторы тут очень странные) 

> Название модификатора характеризует внешний вид («какой размер?», «какая тема?» и т. п. — «размер»: size_s, «тема»: theme_islands), состояние («чем отличается от прочих?» — «отключен»: disabled, «фокусированный»: focused) и поведение («как ведет себя?», «как взаимодействует с пользователем?» — «направление»: directions_left-top).

![Снимок экрана от 2021-07-27 15-56-46](https://user-images.githubusercontent.com/68814270/127126405-6d500f30-ffde-40d7-a6d4-bdf6ca2f02e9.png)
