### ISSUE TITLE
best practice

### ISSUE THREAD

**Issue by Hahahayabanan** [wzdorowa/jQuery-slider#21]
Согласно best practices разработки jQuery плагинов, плагин должен расширять объект jQuery кастомным методом, после вызова которого возвращать jQuery совместимый интерфейс, чтобы не нарушать "цепочку вызовов".

Например, $('slider').myPlugin(someParameters).anotherPlugin().yetAnotherPlugin()

Следовательно, все взаимодействия с плагином должны иметь единую точку входа, и его методы должны вызываться, используя именно интерфейс плагина
Например, так $('slider).myPlugin('setOption', { option: value })

**Comment by Olga-Skoroded** [comment]
Не совсем правильно сделано сейчас) 
Попробуй почитать тут https://habr.com/ru/post/158235/ и тут https://www.sitepoint.com/10-tips-better-jquery-plugins/ 
Если будет сделано правильно, то вот такая конструкция не должна выдавать ошибку: $element.slider(...).css(...)

**Comment by Olga-Skoroded** [comment]
У меня линтер ругается
![Снимок экрана от 2021-08-04 18-25-05](https://user-images.githubusercontent.com/68814270/128173040-bbd398c3-39ce-412c-bd4f-66f24790793b.png)
